# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=70)),
                ('mensaje', models.CharField(max_length=500)),
                ('estado', models.BooleanField(verbose_name=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
